version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgresdb:
    image: postgres:13-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh
      POSTGRES_DB: lock
    ports:
      - "5432:5432"